---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MichalAdorno/spring-cloud-learning
          searchPaths: configuration
        native:
          searchLocations: classpath:offline-config/
server:
  port: 7001